config/routes.rb
Parking::Application.routes.draw do
  devise_for :users

  resources :tickets

  get "home/index"

  authenticate :user do
    root :to => "home#index"
  end

  root :to => "devise/sessions#new"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates_presence_of :folio
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user! 
  
  def index
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.xml
  def index
    @tickets = Ticket.paginate :page => params[:page], :per_page => 5

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.xml
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.xml
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.xml
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to(@ticket, :notice => 'Ticket was successfully created.') }
        format.xml  { render :xml => @ticket, :status => :created, :location => @ticket }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.xml
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to(@ticket, :notice => 'Ticket was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.xml
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to(tickets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/home/_sidebar.html.haml
.block
  %h3 Examples
  %ul.navigation
    %li
      %a.anchor{:href => "#block-text"} Text
    %li
      %a.anchor{:href => "#block-tables"} Tables
    %li
      %a.anchor{:href => "#block-innernav"} Sub-nav
    %li
      %a.anchor{:href => "#block-forms"} Forms
    %li
      %a.anchor{:href => "#block-messages"} Messages
    %li
      %a.anchor{:href => "#block-forms-2"} 2 Cols Forms
    %li
      %a.anchor{:href => "#block-attrtastic"} Attrtastic
    %li
      %a.anchor{:href => "#block-formtastic"} Formtastic
    %li
      %a.anchor{:href => "#block-lists"} Lists
.block.notice
  %h4 Notice Title
  %p Morbi posuere urna vitae nunc. Curabitur ultrices, lorem ac aliquam blandit, lectus eros hendrerit eros, at eleifend libero ipsum hendrerit urna. Suspendisse viverra. Morbi ut magna. Praesent id ipsum. Sed feugiat ipsum ut felis. Fusce vitae nibh sed risus commodo pulvinar. Duis ut dolor. Cras ac erat pulvinar tortor porta sodales. Aenean tempor venenatis dolor.
.block
  .sidebar-block
    %h4 Credits
    %p
      %a{:href => "http://pixelmatrixdesign.com/uniform/"} Jquery Uniform
      \- Uniform look and feel of form elements between browsers
    %p
      %a{:href => "http://glyphish.com/"} Glyphish iconset
      \- Icons of the top-right corner
    %p
      %a{:href => "http://gentleface.com/free_icon_set.html"} Gentleface Wireframe Toolbar Icons
      \- Logout icon
    %p
      %a{:href => "http://www.josbuivenga.demon.nl/museo.html"} Museo font
      \- Sans 500, Sans 500 Italic, 700
    %p
      %a{:href => "http://dribbble.com/"} Dribbble.com
      \- Great place to find inspiration
    %p
      %a{:href => "http://p.yusukekamiyamane.com/"} Fugue icons
      \- Iconset by Yusuke Kamiyamane
    %p
      %a{:href => "http://mynameisraj.com/"} Raj Ramamurthy
      \- Made the dropdown menu and helped me with the buttons!
    %p
      %a{:href => "http://gravityblast.com/"} Andrea Franz
      \- He's the author of the web-app-theme rails plugin

app/views/home/demo.html.erb
<% page_title "My Lovely Page" %>

-----------
<%= icon "delete", :large, :alt => "Delete Item" %>

-----------
<% page_title "About Us" %>

<div class="block">
  <%= secondary_navigation do |n|
    n.item "The Company", about_path("company"), :active => true
    n.item "Our Offices", about_path("offices")
    n.item "Jobs", about_path("jobs"), :class => "highlighted"
  end %>
  <div class="content">
    <h2>About Us</h2>
    <div class="inner">
      <p>We're an amazing company! We do things!</p>
      <p>To find out more, click the tabs above.</p>
    </div>
  </div>
</div>

-----------
<% page_title "News Item 3" %>

<div class="block">
  <div class="content">
    <h2>News Item 3</h2>
    <div class="inner">
      <p>We've got some new news here. Read all about it!</p>
    </div>
  </div>
  <%= breadcrumbs do |b|
    b.item "Home", root_path
    b.item "News", news_path
    b.item "News Item 3", news_path(3), :active => true
  end %> 
</div>

-----------
<% page_title "News Item 3 (Admin Mode)" %>

<div class="block">
  <div class="content">
    <%= controls do |c|
      c.item "Delete", news_path(3), :link_options => { :method => :delete, :confirm => "Really delete News Item 3?" }, :icon => "delete"
      c.item "Edit", edit_news_path(3), :icon => "edit"
    end %>
    <h2>News Item 3</h2>
    <div class="inner">
      <p>We've got some new news here. Read all about it!</p>
    </div>
  </div>
</div>

-----------
<% content_for :head do %>
  <script>
    console.log('This is in the header now.')
  </script>
<% end %>

app/views/home/demo.html.haml
- page_title "My Lovely Page"
\-----------
\#{icon "delete", :large, :alt => "Delete Item"}

\-----------
- page_title "About Us"
.block
  = secondary_navigation do |n|                                    |
      n.item "The Company", about_path("company"), :active => true |
      n.item "Our Offices", about_path("offices")                  |
      n.item "Jobs", about_path("jobs"), :class => "highlighted"   |
    end                                                            |
  .content
    %h2 About Us
    .inner
      %p We're an amazing company! We do things!
      %p To find out more, click the tabs above.
\-----------
- page_title "News Item 3"
.block
  .content
    %h2 News Item 3
    .inner
      %p We've got some new news here. Read all about it!
  = breadcrumbs do |b|                                    |
      b.item "Home", root_path                            |
      b.item "News", news_path                            |
      b.item "News Item 3", news_path(3), :active => true |
    end                                                   |
\-----------
- page_title "News Item 3 (Admin Mode)"
.block
  .content
    = controls do |c|                                                                                                                       |
        c.item "Delete", news_path(3), :link_options => { :method => :delete, :confirm => "Really delete News Item 3?" }, :icon => "delete" |
        c.item "Edit", edit_news_path(3), :icon => "edit"                                                                                   |
      end                                                                                                                                   |
    %h2 News Item 3
    .inner
      %p We've got some new news here. Read all about it!
\-----------
- content_for :head do
  :javascript
    console.log('This is in the header now.')
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Parking Web App

    = stylesheet_link_tag "jquery-ui.css", :cache => true
    = stylesheet_link_tag "formtastic.css", :cache => true
    = stylesheet_link_tag "jquery.tipsy.css", :cache => true
    = stylesheet_link_tag "uniform.default.css", :cache => true

    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js", :cache => true
    = javascript_include_tag "jquery-ui.min.js", :cache => true
    = javascript_include_tag "jquery.scrollTo.js", :cache => true
    = javascript_include_tag "jquery.localscroll.js", :cache => true
    = javascript_include_tag "application.js", :cache => true
    = javascript_include_tag "jquery.tipsy.js", :cache => true
    = javascript_include_tag "jquery.uniform.min.js", :cache => true
 
    = stylesheet_link_tag "base", "themes/activo/style", "override", :cache => true
    = javascript_include_tag :defaults, :cache => true

    = csrf_meta_tag
  %body
    #container
      #header
        .logo
        #user-navigation
          %ul.wat-cf
            %li
              = link_to image_tag('/stylesheets/themes/activo/images/session/home.png', :alt => 'Home', :title => 'Home'), "/"
            %li
              = link_to image_tag('/stylesheets/themes/activo/images/session/account.png', :alt => 'Account', :title => 'Account'), "#"
            %li
              = link_to image_tag('/stylesheets/themes/activo/images/session/config.png', :alt => 'Config', :title => 'Config'), "#"
            %li
              = link_to image_tag('/stylesheets/themes/activo/images/session/logout.png', :alt => 'Logout', :title => 'Logout'), destroy_user_session_path
        #main-navigation
          %ul.wat-cf
            %li{ :class => (params[:controller] == "home" ? "first active" : "first") }
              = link_to "Home", root_path
            %li{ :class => (params[:controller] == "tickets" ? "active" : nil) }
              = link_to "Tickets", tickets_path
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            %p Copyright &copy; #{Time.now.year} Parking Web App.
        #sidebar
          = yield :sidebar

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %title Parking Web App
    = stylesheet_link_tag "base", "themes/activo/style", "override", :cache => true
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/tickets/_form.html.haml
.group
  = f.label :folio, t("activerecord.attributes.ticket.folio", :default => "Folio"), :class => :label
  = f.text_field :folio, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :licenseplate, t("activerecord.attributes.ticket.licenseplate", :default => "Licenseplate"), :class => :label
  = f.text_field :licenseplate, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :note, t("activerecord.attributes.ticket.note", :default => "Note"), :class => :label
  = f.text_area :note, :class => 'text_area'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), tickets_path, :class => "text_button_padding link_button"

app/views/tickets/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", tickets_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_ticket_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_ticket_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Ticket
    .inner
      = form_for @ticket, :url => ticket_path(@ticket), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/tickets/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", tickets_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_ticket_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Tickets
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.ticket.folio", :default => t("activerecord.labels.folio", :default => "Folio"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @tickets.each do |ticket|
          %tr{:class => cycle("odd", "even")}
            %td
              = ticket.id
            %td
              = link_to ticket.folio, ticket_path(ticket)
            %td
              = ticket.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", ticket_path(ticket)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_ticket_path(ticket)}
              |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", ticket_path(ticket), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
          = will_paginate @tickets
- content_for :sidebar, render(:partial => 'sidebar')

app/views/tickets/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", tickets_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_ticket_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Ticket
    .inner
      = form_for :ticket, :url => tickets_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/tickets/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", tickets_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_ticket_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", ticket_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.ticket.folio", :default => t("activerecord.labels.folio", :default => "Folio"))
          \:
        = @ticket.folio
      %p
        %b
          = t("activerecord.attributes.ticket.licenseplate", :default => t("activerecord.labels.licenseplate", :default => "Licenseplate"))
          \:
        = @ticket.licenseplate
      %p
        %b
          = t("activerecord.attributes.ticket.note", :default => t("activerecord.labels.note", :default => "Note"))
          \:
        = @ticket.note
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_ticket_path(@ticket), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), ticket_path(@ticket), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')